spring.application.name=Backend
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mariadb://localhost:3306/featureflagsdb
spring.datasource.username=flagship-user
spring.datasource.password=flagship-password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.jpa.open-in-view=false